name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Setup JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.10
          
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.1
        
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.8
        
      - name: Execute Gradle build
        run: ./gradlew build
        
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.27
        if: always()
        with:
          files: build/test-results/**/*.xml
        
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          
      - name: Commit and push JaCoCo badge
        uses: EndBug/add-and-commit@v8.0.1
        with:
          message: 'Add JaCoCo coverage badge'
          add: '*.svg'
          
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v2.3.1
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/
          
      - name: Build image
        run: ./gradlew jibDockerBuild --image=markets-api
      
